options vfio-pci ids=10de:2507,10de:228e #nvidia gpu video, audio
#options vfio-pci ids=1002:67df,1002:aaf0 #amd prova, non funzionerebbe perche non in iommu gruppo a parte

# This loads vfio when udev loads GPU drivers, (better) alternative to initramfs
# To disable loading vfio I can put nvidia modules in the initramfs modules,
# those will be loaded before udev is able to do anything.
#
# Using this also means that my bind.sh script won't work. To make it work I have to comment these lines temporarily
softdep drm pre: vfio-pci
softdep nvidia pre: vfio-pci
#softdep amdgpu: vfio-pci

#Requires rerunning mkinitcpio I'm pretty sure
